name: Python application

on:
  push:
    branches:
      - main  # 或者你的默认分支名

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
      shell: bash

    - name: Build executables
      run: |
        for file in *.pyw; do
          pyinstaller --onefile --name "${file%.*}" --icon "${file%.*}.ico" "$file"
        done
      shell: bash

    - name: Move executables
      run: |
        mkdir action-generate
        mv ./dist/*.exe ./action-generate/
      shell: bash

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: action
        name: ${{ github.sha }}
        draft: false
        prerelease: false
        files: ./action-generate/*
