name: Python application

on:
  push:
    branches:
      - main  # 或者你的默认分支名

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executables
      run: |
        for file in *.pyw; do
          pyinstaller --onefile --name "${file%.*}" --icon "${file%.*}.ico" "$file"
        done

    - name: Upload executables
      uses: actions/upload-artifact@v2
      with:
        name: Executables
        path: dist/*.exe
